server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:D:\codigos\FIAP-Spring\cervejaria\fiapcervejaria;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    user:
      name: admin
      password: fiap
      roles: ADMIN